version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8093:8093"
    env_file:
      config/.env
  postgres:
    image: ghcr.io/baosystems/postgis:15-3.3
    user: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=L96a1prosniper
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/